// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: protos/piano.proto

package piano

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PianoClient is the client API for Piano service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PianoClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Piano_ConnectClient, error)
}

type pianoClient struct {
	cc grpc.ClientConnInterface
}

func NewPianoClient(cc grpc.ClientConnInterface) PianoClient {
	return &pianoClient{cc}
}

func (c *pianoClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Piano_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Piano_ServiceDesc.Streams[0], "/piano.Piano/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &pianoConnectClient{stream}
	return x, nil
}

type Piano_ConnectClient interface {
	Send(*Note) error
	Recv() (*Note, error)
	grpc.ClientStream
}

type pianoConnectClient struct {
	grpc.ClientStream
}

func (x *pianoConnectClient) Send(m *Note) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pianoConnectClient) Recv() (*Note, error) {
	m := new(Note)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PianoServer is the server API for Piano service.
// All implementations must embed UnimplementedPianoServer
// for forward compatibility
type PianoServer interface {
	Connect(Piano_ConnectServer) error
	mustEmbedUnimplementedPianoServer()
}

// UnimplementedPianoServer must be embedded to have forward compatible implementations.
type UnimplementedPianoServer struct {
}

func (UnimplementedPianoServer) Connect(Piano_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPianoServer) mustEmbedUnimplementedPianoServer() {}

// UnsafePianoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PianoServer will
// result in compilation errors.
type UnsafePianoServer interface {
	mustEmbedUnimplementedPianoServer()
}

func RegisterPianoServer(s grpc.ServiceRegistrar, srv PianoServer) {
	s.RegisterService(&Piano_ServiceDesc, srv)
}

func _Piano_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PianoServer).Connect(&pianoConnectServer{stream})
}

type Piano_ConnectServer interface {
	Send(*Note) error
	Recv() (*Note, error)
	grpc.ServerStream
}

type pianoConnectServer struct {
	grpc.ServerStream
}

func (x *pianoConnectServer) Send(m *Note) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pianoConnectServer) Recv() (*Note, error) {
	m := new(Note)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Piano_ServiceDesc is the grpc.ServiceDesc for Piano service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Piano_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "piano.Piano",
	HandlerType: (*PianoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Piano_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/piano.proto",
}
